---
apiVersion: v1
kind: Namespace
metadata:
    labels:
        app.kubernetes.io/managed-by: score-k8s
        pod-security.kubernetes.io/enforce: restricted
    name: podinfo
---
apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
    name: podinfo
spec:
    args:
        - --port=9898
        - --cert-path=/data/cert
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
    command:
        - ./podinfo
    env:
        - name: PODINFO_UI_COLOR
          value: '#34577c'
        - name: PODINFO_UI_MESSAGE
          value: ""
    image: ghcr.io/stefanprodan/podinfo:latest
