apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
    name: podinfo-kro-minimal-setup
spec:
    image: ghcr.io/stefanprodan/podinfo:6.9.2
    env:
        - name: PODINFO_UI_COLOR
          value: '#34577c'
        - name: PODINFO_UI_MESSAGE
          value: Hello, from ArgoCD and Kro - Created by Developer!
