---
apiVersion: v1
kind: Namespace
metadata:
    labels:
        app.kubernetes.io/managed-by: developer
        pod-security.kubernetes.io/enforce: restricted
    name: podinfo-kro
---
apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
    name: podinfo-kro
    namespace: podinfo-kro
spec:
    args:
        - --port=9898
        - --cert-path=/data/cert
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
    rbacRules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "watch"]
    command:
        - ./podinfo
    env:
        - name: PODINFO_UI_COLOR
          value: '#34577c'
        - name: PODINFO_UI_MESSAGE
          value: Hello, from ArgoCD and Kro - Created by Developer!
    image: ghcr.io/stefanprodan/podinfo:6.9.2
    livenessProbe:
        httpGet:
            path: /healthz
            port: 9898
    readinessProbe:
        httpGet:
            path: /readyz
            port: 9898
    resources:
        limits:
            cpu: 500m
            memory: 512Mi
        requests:
            cpu: 100m
            memory: 128Mi
    route:
        host: localhost
        path: /
        port: 9898
    service:
        ports:
            - name: grpc
              port: 9999
              protocol: TCP
              targetPort: 9999
            - name: http
              port: 9898
              protocol: TCP
              targetPort: 9898
            - name: http-metrics
              port: 9797
              protocol: TCP
              targetPort: 9797
