apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
    name: podinfo-kro-minimal-setup
    namespace: default
spec:
    image: ghcr.io/stefanprodan/podinfo:6.9.2
    livenessProbe:
        httpGet:
            path: /healthz
            port: 9898
    readinessProbe:
        httpGet:
            path: /readyz
            port: 9898
