apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
  name: podinfo-app
  namespace: test
spec:
  name: podinfo-app-kro
  image: ghcr.io/stefanprodan/podinfo:6.9.2
  command:
    - ./podinfo
  args:
    - --port=9898
    - --cert-path=/data/cert
    - --port-metrics=9797
    - --grpc-port=9999
    - --grpc-service-name=podinfo
    - --level=info
    - --random-delay=false
    - --random-error=false
  env:
    - name: PODINFO_UI_COLOR
      value: "#34577c"
    - name: PODINFO_UI_MESSAGE
      value: ""
  ports:
    - name: http
      containerPort: 9898
      protocol: TCP
    - name: http-metrics
      containerPort: 9797
      protocol: TCP
    - name: grpc
      containerPort: 9999
      protocol: TCP
  createHTTPRoute: false