apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-env
  namespace: test
data:
  PODINFO_UI_COLOR: "#34577c"
  PODINFO_UI_MESSAGE: ""
---
apiVersion: kro.run/v1alpha1
kind: Workload
metadata:
  name: podinfo-app
  namespace: test
spec:
  name:       podinfo-app-kro
  image:      ghcr.io/stefanprodan/podinfo:6.9.2
  envConfigMapName: podinfo-env

  # Keep HTTPRoute off for now
  createHTTPRoute: false